disable build since it breaks master
andriod code should not incldue nanohub includes directly like this

device/google/contexthub/util/nanotool/../../firmware/inc/sensors.h:23:10: fatal error: 'plat/inc/taggedPtr.h' file not found
        ^
1 error generated.

Change-Id: If089e5c673379445eeea21c47c769dbc7e8b55c9