firmware: Fix compilation due to lack of assert.h
os/algos/common/math/vec.h:43:38: fatal error: chre/util/nanoapp/assert.h: No such file or directory

Bug: 215535680
Test: make -C device/google/contexthub/firmware/variant/neonkey/

Signed-off-by: Dmitry Shmidt <dimitrysh@google.com>
Change-Id: Iad91c0a0b0fe3c1b49d86ad9d170fe3215a2ea0f