DO NOT MERGE: disable build since it breaks master
andriod code should not incldue nanohub includes directly like this

device/google/contexthub/util/nanotool/../../firmware/inc/sensors.h:23:10: fatal error: 'plat/inc/taggedPtr.h' file not found
        ^
1 error generated.

Change-Id: I4064b9181e9e6217ef5a090957424cc853765fad